#services:
#    App\Services\CommissionFeeSeraCalculator:
#        public: true
#    App\Services\ClientFactory:
#        public: true
#    App\Services\CurrencySeraConverter:
#        public: true
#    App\Services\CsvParser:
#        public: true
framework:
    test: ~